### ISSUE TITLE
At a glance disappears on custom grid options...

### ISSUE THREAD

**Issue by Huexxx** [Evolution-X-AOSP/packages_apps_Launcher3#43]
Hi.

With custom grids with # of rows > 5 smartspace is not visible.

It works fine with 2x2, 3x3, 4x4, 4x5 and 5x5, but fails to show on the rest.

Smartspace is there... because space is ocuppied and you can get into calendar tapping into it... but you cannot see it.

Regards.

**Comment by Huexxx** [comment]
I have already tried to remove old wigget on those grids, as done on "Launcher3: Implement Smartspace" without sucess...

    <appwidget
        launcher:packageName="com.google.android.googlequicksearchbox"
        launcher:className="com.google.android.apps.gsa.staticplugins.smartspace.widget.SmartspaceWidgetProvider"

**Comment by Huexxx** [comment]
I've also tried to use default 5x5 and 6x5 for all 5 and 6 columns workspaces without sucess.

**Comment by joeyhuab** [comment]
Should be fixed with this: https://github.com/Evolution-X/packages_apps_Launcher3/commit/2d48642a014afd3300af54faafb8c56328b4c7ec
