### ISSUE TITLE
Top Shadow string not respected every wallpaper change

### ISSUE THREAD

**Issue by manosdoc** [Evolution-X-AOSP/packages_apps_Launcher3#50]
I don't know if thats official source side.
If you want to disable Top shadow on home screen, you need to re enable and disable on every wallpaper change because it sets on by itself.
[topshadow.log](https://github.com/Evolution-X/packages_apps_Launcher3/files/12046889/topshadow.log)

**Comment by joeyhuab** [comment]
https://github.com/Evolution-X/packages_apps_Launcher3/commit/0dcf362c79069dba2bcd266dab7a571f55a8fba3

It's because of this. I'll remove it.
